name: Build Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "package.json"
      - "package-lock.json"
      - "index.js"
      - ".github/workflows/**"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Confirm workflow trigger
        run: echo "GitHub Actions foundation is working"

      
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      
      - name: Build Docker Image
        run: docker build -t chetanasivadurga/ai-devops:${{ github.run_number }} .

      - name: Tag Docker Image as latest
        run: docker tag chetanasivadurga/ai-devops:${{ github.run_number }} chetanasivadurga/ai-devops:latest

      # ==== ROLE D: Push to Docker Hub ====
      - name: Push Docker Image (versioned)
        run: docker push chetanasivadurga/ai-devops:${{ github.run_number }}

      - name: Push Docker Image (latest)
        run: docker push chetanasivadurga/ai-devops:latest


